### ISSUE TITLE
Fatal error: Uncaught Error: Class 'EcomPHP\TiktokShop\Auth' not found

### ISSUE THREAD

**Issue by sunil11475-dev** [EcomPHP/tiktokshop-php#22]
I am getting this error, Please help

Fatal error: Uncaught Error: Class 'EcomPHP\TiktokShop\Auth' not found in /libraries/tiktok/src/Client.php:119

**Comment by nVuln** [comment]
make sure you install this package by composer, use command `composer require ecomphp/tiktokshop-php` to install it

**Comment by sunil11475-dev** [comment]
Thanks, I have remove all package and re-install and it working now again.

Can you please check if this right - from your readme file.

```
Get authorized Shop ID
$access_token = $token['access_token'];
$client->setAccessToken($access_token);

$authorizedShopList = $client->Shop->getAuthorizedShop();
```
Getting below error - 
`Fatal error: Uncaught EcomPHP\TiktokShop\Errors\TiktokShopException: Invalid resource Shop in /libraries/Tiktok/vendor/ecomphp/tiktokshop-php/src/Client.php:238`

**Comment by sunil11475-dev** [comment]
No worries figure it out :)

```
		$client->setAccessToken($access_token);
		$authorizedShopList= $client->Authorization->getAuthorizedShop();
```
