### ISSUE TITLE
param create_time_ge type invalid,actual type is:string,expected type is:int64

### ISSUE THREAD

**Issue by decha5876** [EcomPHP/tiktokshop-php#23]
Hello
i call Orderlist (with period)
$client->Order->getOrderList([
                'create_time_ge' => $time_before,
                'create_time_lt' => $timest,
                'page_size' => (int)10,
                'sort_field' => 'create_time',
                'page_token' => $next_cursor,
            ]);

this shown **param create_time_ge type invalid,actual type is:string,expected type is:int64**

how to fix it

**Comment by nVuln** [comment]
how is your `$time_before` variable?

**Comment by decha5876** [comment]
`$time_before` yes is variable

//
$timest = Carbon::now()->timestamp;
$time_bef1 = date('Y-m-d', strtotime(date('Y-m-d') . ' -5 day'));
$time_before = (int)strtotime($time_bef1);

**Comment by nVuln** [comment]
in new api, they split into 2 kind of param, query for paginator and body params for filter content, let try
```php
$client->Order->getOrderList([
    'page_size' => (int)10,
    'sort_field' => 'create_time',
    'page_token' => $next_cursor,
], [
    'create_time_ge' => $time_before,
    'create_time_lt' => $timest,
]);

**Comment by decha5876** [comment]
it's worked
thank you so much
