### ISSUE TITLE
Fulfillment.php - markPackageAsShipped

### ISSUE THREAD

**Issue by sunil11475-dev** [EcomPHP/tiktokshop-php#26]
When i am making call for markPackageAsShipped, getting below message - 

```
    [*message] => This interface cannot be used in this region or this business type. Please don't use the api.
    [Exceptionstring] => 
    [*code] => 21008106
```

**Comment by nVuln** [comment]
what problem? I saw that is clearly message, if you need anymore information about this please write a ticket to tiktokshop support

**Comment by sunil11475-dev** [comment]
@nVuln , I know it too much too ask. can you please guide me how to mark shipped the order. I have trying call from Fulfillment but there many function which little confusing.

I have used shipPackage which change the status to Awaiting Collection, its been 24 hours and it showing Awaiting Collection. there is no option mark shipped on order.

Then i tried updateShippingInfo funciton also but it allows only once to update the tracking. 

I think i am doing some wrong. if you have any example which i can use?

**Comment by nVuln** [comment]
@sunil11475-dev `Mark Package As Shipped` currently available in US region  only
use `Ship Package` API maybe correct way, if you used `Seller Shipping` type, you need provide correct tracking number and shipment provider id
if your tracking number status shown shipped but tiktok not updated, please ticket to tiktok support and ask them, maybe some delay on their system

**Comment by sunil11475-dev** [comment]
Thanks for your reply. When i am using Ship Package api to dispatch the order. its update the details on tiktok shop but returning empty response.

Request - 
```
			$resp = $client->Fulfillment->shipPackage($package_id, $handover_method = 'PICKUP',
			$pickup_slot = [
			    "end_time"=> strtotime("now"),
			    "start_time"=> strtotime("-5 hours")
			],
			$self_shipment = [
			"shipping_provider_id"=> $shipping_provider_id,
			"tracking_number"=> $tracking_number
			]);
```
Response - 
`array()
`
Any solution for this?
