### ISSUE TITLE
"JSON Parsing Error Using $auth->getToken()"

### ISSUE THREAD

**Issue by Nhaqua** [EcomPHP/tiktokshop-php#29]
I'm encountering an issue where I receive a JSON parsing error when using the $auth->getToken() function in my code. The exact error message is:
`{
"error": "Unable to parse response string as JSON"
}`
However, when I directly run the link in the URL, it seems to accept the JSON response correctly. The issue only arises when I use the $auth->getToken() function.
I am using `$client->useSandboxMode();`

**Comment by nVuln** [comment]
since API version 202309, tiktokshop sandbox server stop worked for unknown reason (I wrote a ticket to TikTok Shop Partner and still waiting their response)
please use production environment for testing
