### ISSUE TITLE
Cannot install on other projects which require guzzle 6.x

### ISSUE THREAD

**Issue by thietdv** [EcomPHP/tiktokshop-php#31]
Got error while installing the module on a Symfony application
.
`  Problem 1
    - Root composer.json requires ecomphp/tiktokshop-php ~2.1.0 -> satisfiable by ecomphp/tiktokshop-php[v2.1.0, v2.1.1, v2.1.2].
    - ecomphp/tiktokshop-php[v2.1.0, ..., v2.1.2] require guzzlehttp/guzzle ^7.3 -> found guzzlehttp/guzzle[7.3.0, ..., 7.9.x-dev] but the package is fixed to 6.5.8 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
`
.
Does it require guzzlehttp/guzzle ^7.3 or 6.x is enough?

**Comment by nVuln** [comment]
already added support for guzzle 6.5 in `v2.2.0`

**Comment by thiet-vmo** [comment]
Thank you so much @nVuln

**Comment by thietdv** [comment]
@nVuln thank you so much
