### ISSUE TITLE
cannot call $client->CustomerService->getConversations()

### ISSUE THREAD

**Issue by dangnguyenvan** [EcomPHP/tiktokshop-php#32]
error message you should apply auth pkg for this api

**Comment by dangnguyenvan** [comment]
@nVuln help me

**Comment by nVuln** [comment]
Customer Service API is inactive by default and the partner/ ISV has to apply for access, which requires approval from your Account Manager or Partner Manager to activate the API to build applications.

more detail: https://partner.tiktokshop.com/docv2/page/659645f9a46cdd02bc8aeacf
