### ISSUE TITLE
Fatal error: Uncaught Error: Class "EcomPHP\TiktokShop\Client" not found

### ISSUE THREAD

**Issue by Mikazuki1234** [EcomPHP/tiktokshop-php#33]
i had create a view.php in src folder 
include:

use EcomPHP\TiktokShop\Client;

$app_key = 'your app key';
$app_secret = 'your app secret';

$client = new Client($app_key, $app_secret);

**Comment by nVuln** [comment]
install this library via composer ```composer require ecomphp/tiktokshop-php```
or you need manual include all .php in this package before using

**Comment by Mikazuki1234** [comment]
in vscode paste (composer require ecomphp/tiktokshop-php) at terminal?
