### ISSUE TITLE
auth链接问题

### ISSUE THREAD

**Issue by TOD-nights** [EcomPHP/tiktokshop-php#35]
从六月三号开始,在点击italy的next按钮后
 
 
![image](https://github.com/EcomPHP/tiktokshop-php/assets/66124749/cbe1e072-29c2-4028-92b2-45b962489378)

弹出了这个界面
 
![image](https://github.com/EcomPHP/tiktokshop-php/assets/66124749/d2c82733-0ea7-49f7-a1f5-5aaf7eb5f078)

之前是可以正常验证的,shop已经是登入状态,host文件也更新了,每条filter我都试过了一遍

https://seller-it.tiktok.com/services/market/custom-authorize/7364311xxxxxxxxx?shop_region=IT

是可以正常用的

**Comment by nVuln** [comment]
I think you should contact tiktok for more detail
