### ISSUE TITLE
cant find eu server now

### ISSUE THREAD

**Issue by TOD-nights** [EcomPHP/tiktokshop-php#37]
![image](https://github.com/EcomPHP/tiktokshop-php/assets/66124749/5db1d7ac-1a93-4774-bde3-90f2a45628bb)

**Comment by nVuln** [comment]
add more target market in `https://partner.tiktokshop.com/service/list/`

**Comment by TOD-nights** [comment]
> add more target market in `https://partner.tiktokshop.com/service/list/`
added,but still cant find
![image](https://github.com/EcomPHP/tiktokshop-php/assets/66124749/a4da504a-21c0-4290-983b-f2dc6f867323)
![image](https://github.com/EcomPHP/tiktokshop-php/assets/66124749/65990e59-b59c-47a5-9e4d-ccd7ed611c63)

**Comment by nVuln** [comment]
if re-built authorization url generated by this plugin not worked, please try use that URL
<img width="395" alt="Screenshot 2024-06-16 at 2 53 58 AM" src="https://github.com/EcomPHP/tiktokshop-php/assets/54855446/2c0a5e25-d779-40ca-ab82-e7bd8ca96d1c">

in case that URL still not worked too, please open ticket to tiktok customer service

**Comment by TOD-nights** [comment]
that URL work ,i will try to change url from auth.php, thank you
