### ISSUE TITLE
$client->Order->getOrderDetail

### ISSUE THREAD

**Issue by conmale289** [EcomPHP/tiktokshop-php#39]
I'm encountering an inconsistency when calling TikTokShop APIs. The getAuthorizedShop function executes successfully, but attempting to access getOrderDetail throws a TokenException.

The error message indicates a missing authentication package (you should apply auth pkg for this api).

Fatal error: Uncaught EcomPHP\TiktokShop\Errors\TokenException: you should apply auth pkg for this api

**Comment by nVuln** [comment]
You need open order detail permission for your app
Please check it on tiktok shop partner center

**Comment by conmale289** [comment]
Thanks for your response!
