### ISSUE TITLE
$client->Authorization->getAuthorizedShop();

### ISSUE THREAD

**Issue by anika-tam** [EcomPHP/tiktokshop-php#40]
I would like to get get_authorized_shop, i try to use this $client->Authorization->getAuthorizedShop(), but I got an error.
I need your help.
this my error.
array:3 [
  "code" => 105005
  "message" => "you should apply auth pkg for this api"
  "request_id" => "20240710170328026B85572D809D2BFFC5"
],

Thank you.

**Comment by nVuln** [comment]
Upload your code please

**Comment by anika-tam** [comment]
Thank you for your response.
Here is two sample code.
1. follow your infomation.
$access_token = $token['access_token'];
$client->setAccessToken($access_token);

$authorizedShopList = $client->Authorization->getAuthorizedShop();
2. This is my code.
$params = [
            'timestamp' => $timestamp,
            'app_key' => $app_key,
            'access_token' => $access_token,
            'shope_id' => 7495830601840691588
        ];
        
        $path = "/api/shop/get_authorized_shop";
        $sign = $this->signature($path, $params ,$access_token);

        $apiEndpoint = 'https://open-api.tiktokglobalshop.com' . $path;
    
        // Construct the query parameters
        $queryParams = http_build_query([
            'app_key' => $app_key,
            'access_token' => $access_token,
            'sign' => $sign,
            'timestamp' => $timestamp,
            'shop_id' => 7381139277420594949,
        ]);

        $response = Http::withHeaders([
            'Content-Type' => 'application/json',
        ])->get($apiEndpoint, $queryParams);

        print_r($response);

public function signature($path, $params, $app_secret, $requet_method = 'GET', $requet_type = "normal", $body = '')
    {
        $arr_params = [];
        if(!is_array($params))
        {
            parse_str($params, $arr_params);
        }
        ksort($arr_params);

        $input = '';
        foreach($arr_params as $key => $value)
        {
            $input .= $key . $value;
        }

        if ($requet_method !='GET' && $requet_type != 'multipart/form-data') {
            $input .= $body;
        }
        $input = $path . $input;

        $input = $app_secret . $input . $app_secret;
        
        return bin2hex(hash_hmac('sha256', $input, $app_secret, true));
    }

**Comment by nVuln** [comment]
I don't understand, but error `you should apply auth pkg for this api` mean your app don't have permission to access this api
please double check it on https://partner.tiktokshop.com/service/list/

**Comment by anika-tam** [comment]
I'll double-check the policy. Thank you for your response!
