### ISSUE TITLE
List all existing products?

### ISSUE THREAD

**Issue by cyril94440** [EcomPHP/tiktokshop-php#43]
Hi there 
Thanks for your excellent work.

Can we list all existing products and sellers with this library ? I am wondering how services like kalodata are able to have metrics about the number of products sold per tiktok accounts for example. 

Thank you very much

**Comment by nVuln** [comment]
this library use tiktokshop api to manage `your seller account`
to list all your products, you can use `search products` api:  [more detail here](https://partner.tiktokshop.com/docv2/page/65854ffb8f559302d8a6acda)

code example to get all products:
```php
use EcomPHP\TiktokShop\Client;

$client = new Client('app key', 'app secret');
$client->setAccessToken('granted access token');

$products = $client->Product->searchProducts([
    'page_size' => 100,
], [
    'status' => 'ALL'
]);
```

more filter you can see on api detail above

**Comment by cyril94440** [comment]
> this library use tiktokshop api to manage `your seller account` to list all your products, you can use `search products` api: [more detail here](https://partner.tiktokshop.com/docv2/page/65854ffb8f559302d8a6acda)
> 
> code example to get all products:
> 
> ```
> use EcomPHP\TiktokShop\Client;
> 
> $client = new Client('app key', 'app secret');
> $client->setAccessToken('granted access token');
> 
> $products = $client->Product->searchProducts([
>     'page_size' => 100,
> ], [
>     'status' => 'ALL'
> ]);
> ```
> 
> more filter you can see on api detail above

Thanks for your answer!
If I am not mistaken, this is just to search the product of my seller account, but I am wondering how services like Kalodata are able to list all products on the platform.

From your answer, it looks like this library can't do it. So, I'm just now wondering where we could find such data.

Thanks

**Comment by nVuln** [comment]
this library used legal API provided by Tiktokshop
you need looking for crawling tool
