### ISSUE TITLE
useVersion is invalid

### ISSUE THREAD

**Issue by dishcheng** [EcomPHP/tiktokshop-php#46]
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/02f43f23-3611-4b02-88a8-ea75bcf59d52">

<img width="861" alt="image" src="https://github.com/user-attachments/assets/79c017e4-8113-4aa4-914e-9aa21deb4294">

Hello,why I have use`useVersion(202405)` like this but however  print is `202309`

lumen8.3.4 + `version 2.5.2`

**Comment by nVuln** [comment]
we have unit test for this feature and it's always passed
https://github.com/EcomPHP/tiktokshop-php/blob/02780fadd3261c8a192c3596e3a435e0bce83584/tests/ResourceTest.php#L63

an error above mean you need apply permission to call that API, "affiliate" in your case

**Comment by dishcheng** [comment]
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/b819c279-a375-4c87-8bd3-d6659a008b0a">
Seems here,because default version is 202309 ,but `AffiliateSeller` $minimum_version is 202405, so when you use `useVersion` first time conflict here?

**Comment by dishcheng** [comment]
![image](https://github.com/user-attachments/assets/16b7e5ee-a71c-4711-840f-087df419d7b9)
<img width="1679" alt="image" src="https://github.com/user-attachments/assets/42363bee-1001-47b4-a1ca-2c836086eda7">

Error seems because default version is 202309 ,but `AffiliateSeller` $minimum_version is 202405, so when you use `useVersion` first time conflict here?

**Comment by nVuln** [comment]
hmm, please try below code, it will set api version 202405 in every api call

```php
$store_client = TiktokService::getClient();
$store_client->useVersion(202405);

$response = $store_client->AffiliateSeller->searchSellerAffiliateOrders();
```

I'll try different way to deal with that api version in future update

**Comment by dishcheng** [comment]
> ```
> $store_client = TiktokService::getClient();
> $store_client->useVersion(202405);
> ```

Yeah,it works ,thanks.
