### ISSUE TITLE
The getProductList function was not found

### ISSUE THREAD

**Issue by czhixin** [EcomPHP/tiktokshop-php#49]
Hi，The Demo

> $products = $client->Product->getProductList([
>     'page_size' => 50,
> ]);

getProductList function was not found

**Comment by nVuln** [comment]
sorry it's outdated example, for lookup product list, you can use searchProducts api here: https://partner.tiktokshop.com/docv2/page/65854ffb8f559302d8a6acda?external_id=65854ffb8f559302d8a6acda

```php
$products = $client->Product->searchProducts([
   'page_size' => 10,
]);
```
